--Write a query to join the employees table (Employee_id, Name, salary, Manager_id)
--with the manager table(manager_id,name,city,salary),
--provided that the salary of employees is greater than 50000 and there should be no null
values.
--(The common column between the two tables is manager_id)
select e.Employee_id, e.Name, e.salary, e.Manager_id, m.name AS Manager_name, m.city
from employees e
inner join manager m on e.Manager_id = m.manager_id
where e.salary > 50000
and e.Manager_id is not NULL
and m.manager_id is not NULL;
--Que2: What will be the output of the following Query?
SELECT * from employees e
LEFT JOIN manager m
ON e.manager_id=m.manager_id
ORDER BY manager_id;
--Ans: This will give us an error because we have not specified
--from which table the manager_id is coming
/*Que3: From the SALESMEN (Salesmen_id,name,city,commission) and
ORDERS tables(order_num,purchase_amt,date,salesmen_id,customer_id)
write a SQL query to find all the orders issued by the salesman “John"
Return order_no, purchase_amt, order_date, customer_id, and salesman_id.*/
select o.order_num, o.purchase_amt, o.date as order_date, o.customer_id, o.salesmen_id
from ORDERS o
join SALESMEN s on o.salesmen_id = s.Salesmen_id
where s.name = 'John';
/*Que4: From the SALESMEN and ORDERS tables write a SQL query to find all orders
generated by
Bangalore-based salesmen. Return order_no, purchase_amt, order_date, customer_id,
salesman_id.*/
select o.order_num, o.purchase_amt, o.date as order_date, o.customer_id, o.salesmen_id
from ORDERS o
join SALESMEN s on o.salesmen_id = s.salesmen_id
where s.city = 'Bangalore';
/*Que5: We have 2 Employee tables from 2 different states write a query to combine the output
of
each table.*/
select Employee_id, Name, State
from EmployeeTable1
union
select Employee_id, Name, State
from EmployeeTable2;
/* Que6: Write a query to get employee_id,name and salary of all the employees from the
employees table
(employee_id, name, city,state, country,salary) where countries are “india” and “US” using the
UNION operator.*/
select employee_id, name, salary
from employees
where country = 'India'
union
select employee_id, name, salary
from employees
where country = 'US';
/*Que7: Write a query to display the maximum and minimum salaries of employees from the
Employees table
(Employee_id, name,department,join_date,city, salary) hired 1 year ago.
*/
select max(salary) as max_salary, min(salary) as min_salary
from Employees
where join_date >= CURRENT_DATE - INTERVAL '1 year';
/*Que8: Write a query to display employees whose salary is greater than
the average salary of their department.*/
select * from Employees e
where e.salary > (
select avg(salary)
from Employees
where department = e.department
);
/*Que9: From the EMPLOYEES table(Employee_id, name,department,join_date,city, salary),
create a view for those employees who belong to the city of Delhi.*/
create view DelhiEmployees as
select *
from Employees
where city = 'Delhi';
/*Que10: From the EMPLOYEES table(Employee_id, name,department,join_date,city, salary),
create an INDEX on employee_id column. */
create index idx_employee_id on Employees (employee_id);